apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      containers:
        - name: {{ .Values.component }}
          image: 512646826903.dkr.ecr.us-east-1.amazonaws.com/frontend:v1.0.5
          imagePullPolicy: Always
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "750m"
